# Generated by Django 3.2.18 on 2024-11-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('Basquete', 'Basquete'), ('Futsal', 'Futsal'), ('Handebol', 'Handebol'), ('Vôlei', 'Vôlei'), ('Atletismo', 'Atletismo')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='participante',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=50, verbose_name='Turno disponível para treino'),
        ),
    ]
