# Generated by Django 3.2.18 on 2024-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20241106_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='nome_time',
            field=models.CharField(default='Time Padrão', max_length=100),
        ),
    ]
